### ISSUE TITLE
An error when finetuning.

### ISSUE THREAD

**Issue by dufan175** [sunlicai/MAE-DFER#10]
Hi, Sorry to bother you again. I was able to fine-tune on a small dataset and get good results, but when I increased the amount of data on the dataset, I got an error and all the experimental parameter settings didn't change, it seems to be caused by the index of the dataset, but I checked the dataset and didn't find anything wrong, do you know why. Looking forward to your reply.
Here is the log:

optimizer settings: {'lr': 3.125e-05, 'weight_decay': 0.0, 'eps': 1e-08, 'betas': [0.9, 0.999]}
Use step level LR scheduler!
Set warmup steps = 745
Set warmup steps = 0
Max WD = 0.0500000, Min WD = 0.0500000
criterion = SoftTargetCrossEntropy()
Auto resume checkpoint: 
Start training for 100 epochs
==> Note: Error 'list index out of range' occurred when load video of '/opt/data/private/dataset_5clip_10s/train/1/1680777543675809792/4'!!!
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'run_class_finetuning.py', '--local_rank=1', '--model', 'vit_base_dim512_no_depth_patch16_160', '--depth', '16', '--data_set', 'MYDATA', '--nb_classes', '2', '--data_path', './saved/data/mydata/all_scenes', '--finetune', './saved/model/pretraining/voxceleb2/videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49.pth', '--log_dir', './saved/model/finetuning/mydata/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_lr_1e-3_epoch_100_size160_sr4_classify_token_type_region_server164', '--output_dir', './saved/model/finetuning/mydata/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_lr_1e-3_epoch_100_size160_sr4_classify_token_type_region_server164', '--batch_size', '4', '--num_sample', '1', '--input_size', '160', '--short_side_size', '160', '--save_ckpt_freq', '1000', '--num_frames', '16', '--sampling_rate', '4', '--opt', 'adamw', '--lr', '1e-3', '--opt_betas', '0.9', '0.999', '--weight_decay', '0.05', '--epochs', '100', '--dist_eval', '--test_num_segment', '2', '--test_num_crop', '2', '--attn_type', 'local_global', '--lg_region_size', '2', '5', '10', '--lg_classify_token_type', 'region', '--num_workers', '0']' returned non-zero exit status 255.

**Comment by sunlicai** [comment]
It seems that some video samples do not contain enough frame images in their directories (probably no images). You'd better check this sample '/opt/data/private/dataset_5clip_10s/train/1/1680777543675809792/4' to verify the problem. In addition, you need to exclude all kinds of these samples during pre-processing.

**Comment by dufan175** [comment]
The error was caused by the format of images, i have solved this, thanks for your reply. Have a nice day!
