### ISSUE TITLE
About num_frames and sampling_rate.

### ISSUE THREAD

**Issue by dufan175** [sunlicai/MAE-DFER#13]
I'm sorry to bother you again and again. The frame of each video in my dataset is around 64. In the script, num_frames is set to 16 and sampling_rate is set to 4, this means that each video needs to be at least 16*6=64 frames, right? But when the sampling_rate is set to greater than 4, sunch as 6 or 8, the required frame is greater than the frame of each video in my dataset, the finetuning can still proceed. I want to know why. Is it my my misunderstanding of num_frames and sampling_rate? 
Looking forward to your reply

**Comment by sunlicai** [comment]
If the number of frames is less than the required, the code will pad the last frame.

https://github.com/sunlicai/MAE-DFER/blob/8cd44d5e6710cf9bb45a30c4d50832fe68a96f75/kinetics.py#L571-L574

**Comment by dufan175** [comment]
OK, thank you very much.

**Comment by dufan175** [comment]
Can I use the pre-trained model for binary classification testing directly? If so, how can I do?
Looking forward to your reply and thank you very much!

**Comment by youcaiSUN** [comment]
Yes, you can.  All you need to do is to simply change the number of classes to 2.
