### ISSUE TITLE
in-place operation error?

### ISSUE THREAD

**Issue by Zander-J** [sunlicai/MAE-DFER#15]
When I want to finetune the model with this code, there seem to be an **in-place** operation in [modeling_finetune.py#L299](https://github.com/sunlicai/MAE-DFER/blob/8cd44d5e6710cf9bb45a30c4d50832fe68a96f75/modeling_finetune.py#L299), which could be written as `x[:, 0] = f(x[:, 0])`. 
So pytorch (2.0.0+cu118 in my server) raises a runtime error as follows:

> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 8, 512]], which is output 0 of AsStridedBackward0, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Then I change [modeling_finetune.py#L295](https://github.com/sunlicai/MAE-DFER/blob/8cd44d5e6710cf9bb45a30c4d50832fe68a96f75/modeling_finetune.py#L295)
```python
messenger_tokens = rearrange(x[:,0], '(b n) c -> b n c', b=b) # attn on 'n' dim
```
to
```python
messenger_tokens = rearrange(x[:,0].clone(), '(b n) c -> b n c', b=b) # attn on 'n' dim
```
, and the program is able to process. I don't know if this is caused by the version of pytorch? Or does this modification may have impact on the final performance?

**Comment by sunlicai** [comment]
Hi @A91A981E, thanks for your interest in our work! 

This issue is caused by the version of pytorch (default is pytorch1.7). It has been raised in [pervious isssue](https://github.com/sunlicai/MAE-DFER/issues/3#issuecomment-1809834219) which gives similar solution. Your modification shall not have impact on the final performance.
