### ISSUE TITLE
Consultation on the preprocessing of DFEW datasets

### ISSUE THREAD

**Issue by NKBpower** [sunlicai/MAE-DFER#17]
Hello, I am very interested in your work, but I have some questions about the comments in dfew. py in your pre-processing file because you wrote # org: original frames in jpg_256 in line 13 of the comments, not temporally aligned in jpg_224_16f， But when I applied for the dataset again, I couldn't find the file in the jpg_256 folder and only found jpg_224. I would like to ask if you used the original frame folder jpg_224 or the video folder?

**Comment by NKBpower** [comment]
I hope you can answer my question, thank you very much for your help.

**Comment by sunlicai** [comment]
Hi, sorry for the confusion. It should be clarified that the real facial image resolution in jpg_224 is 256x256. Thus, I rename this folder and keep the content unchanged.
---- Replied Message ----
From ***@***.***> Date 10/13/2024 10:33 To ***@***.***> Cc ***@***.***> Subject Re: [sunlicai/MAE-DFER] Consultation on the preprocessing of DFEW datasets (Issue #17) 
I hope you can answer my question, thank you very much for your help.

**Comment by NKBpower** [comment]
OK，i get it，thanks for your help.
