### ISSUE TITLE
Is VideoMAE model available?

### ISSUE THREAD

**Issue by hellojialee** [sunlicai/MAE-DFER#2]
Great work! Are pre-trained VideoMAE models available?

**Comment by sunlicai** [comment]
Sorry for late reply! For now, the pre-trained VideoMAE model are not available, but we plan to release it at the end of this month. 

Stay tuned, Thanks!

**Comment by cyinen** [comment]
Hi，a month has already passed, will the  pre-trained VideoMAE  model still be released?

**Comment by sunlicai** [comment]
Hi! We're really sorry because we lost the pre-trained ckpt in the original server. But we're re-training it and the ckpt will be available in this month.

**Comment by sunlicai** [comment]
Hi @hellojialee, @cyinen ! Sorry for the late reply!

The pre-trained VideoMAE model is availabe [here](https://drive.google.com/file/d/1rs9UhEbvQR9rwKQcUFDrVijCc62J-Pbs/view?usp=sharing).
