### ISSUE TITLE
Some problems encountered in replicating experimental results on DFEW datasets

### ISSUE THREAD

**Issue by zhaominghui123** [sunlicai/MAE-DFER#5]
@youcaiSUN 
Hello author ~ I really like your work, fantastic job, I would like to try to perform a reproduction of the results in the paper, such as the dfew dataset.
I have changed the parameters in run_class_finetuning.py from the dfe.out file, and I have downloaded the pre-trained model to the specified folder. But I ran into a problem: AttributeError: 'Namespace' object has no attribute 'pretrained_cfg'. I try to add this parameter during model creation, and no matter what type of value I set, TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'. So I want to know how and where 'pretrained_cfg' should be set .
Also, I didn't use a distributed unit, so I removed the code in question, wondering if this was the reason for the error.
Another problem is that I repeat the experiment to run run_class_finetuning.py directly, I don't know if there is any other preparation work I missed.
I am a beginner, so the question may be a little too simple, hope you have time to answer it.
Thank you very much for reading ~ looking forward to your reply!

**Comment by youcaiSUN** [comment]
Hi @zhaominghui123! Thanks for your interest in our work!

Actually, I did not encounter your problem before.

Could you provide your console output or running log file to help me to figure it out?

Thanks!

**Comment by zhaominghui123** [comment]
Traceback (most recent call last):
  File "run_class_finetuning.py", line 666, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 319, in main
    model = create_model(
  File "/home/Disk-2T/base/anaconda3/envs/hui/lib/python3.8/site-packages/timm/models/_factory.py", line 114, in create_model
    model = create_fn(
  File "/home/zhaominghui/MAE-DFER-master/modeling_finetune.py", line 600, in vit_base_dim512_no_depth_patch16_160
    model = VisionTransformer(
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

@youcaiSUN    This is the error I get when I run the 'run_class_finetuning.py' file

**Comment by youcaiSUN** [comment]
I believe it's due to the mismatch of timm version. The required is timm==0.4.12, please check yours.

**Comment by zhaominghui123** [comment]
Thank you very much for your answer, the problem has been solved @youcaiSUN

**Comment by youcaiSUN** [comment]
Nice! Feel free to ask me if you have any questions.
