### ISSUE TITLE
Model checkpoints for inference

### ISSUE THREAD

**Issue by kumar-devesh** [sunlicai/MAE-DFER#6]
Thanks for releasing the code! Do you plan to make trained model checkpoints available for inference?

**Comment by youcaiSUN** [comment]
Hi, @kumar-devesh  ! Thanks for your interest in our work!

We upload the fine-tuned models in early December. Stay tuned!

**Comment by sunlicai** [comment]
Hi! The fine-tuned models across five folds on DFEW are available. You can check them in README.md.
