### ISSUE TITLE
Code for inference.

### ISSUE THREAD

**Issue by dufan175** [sunlicai/MAE-DFER#7]
Thanks for the great work! I am wondering whether the inference code has been released so that we can quickly test out the model on customized videos?

**Comment by youcaiSUN** [comment]
Hi! Thanks for your interest in our work!

Sorry, for now, we do not support sample-level inference. However, you can test your fine-tuned model on customized videos in batch level by using '--eval' option in the command line. Note that you should prepare your videos in a csv file (i.e., video path + label) for testing in a similar way with fine-tuning.

Best,
Licai

**Comment by dufan175** [comment]
Ok, thanks for your reply, we wil try.

**Comment by dufan175** [comment]
Hello, we are currently preparing to use your code for fine-tuning. We noticed the data processing in your paper. May I ask if we will directly use all the data without processing as input, or if the data needs to be preprocessed by ourselves before input? In other words, has your code integrated the data preprocessing part? 
Looking forward to your reply, thank you.

**Comment by youcaiSUN** [comment]
The preprocessing is mainly face detection and alignment (we adopt openface to do this job if no processed faces provided by the official dataset，such as crema-d，ravdess，and enterface). After this, you can prepare your input data according to Data Preparation section (i.e., a csv file containing data path and label). Then you can adapt the example running script and run it.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/05/2023 14:02 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [sunlicai/MAE-DFER] Code for inference. (Issue #7) |

Hello, we are currently preparing to use your code for fine-tuning. We noticed the data processing in your paper. May I ask if we will directly use all the data without processing as input, or if the data needs to be preprocessed by ourselves before input? In other words, has your code integrated the data preprocessing part?
Looking forward to your reply, thank you.

**Comment by dufan175** [comment]
OK，thank you! I also have one more question, which is what you said in your paper, "we extract 16 frames from each video clip using a temporal stride of 4", does this process need to be done by ourselves. Or do we just need to put all the data after face detection and alignment into a folder?

**Comment by sunlicai** [comment]
Hi! The code will handle it. All you need is to put the data into the folder.

**Comment by dufan175** [comment]
Ok, thank you.

**Comment by dufan175** [comment]
Hi! I have an error.When I run "finetune_local_global_attn_depth16_region_size2510_with_diff_target_164" with my own dataset, an error apperance,it seems the dataset error. Do you know what the reason is?
Traceback (most recent call last):
  File "run_class_finetuning.py", line 679, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 256, in main
    dataset_val, _ = build_dataset(is_train=False, test_mode=False, args=args)
  File "/opt/data/private/MAE-DFER-master/datasets.py", line 224, in build_dataset
    args=args)
  File "/opt/data/private/MAE-DFER-master/kinetics.py", line 331, in __init__
    self.label_array = list(cleaned.values[:, 1])
IndexError: index 1 is out of bounds for axis 1 with size 1
Number of the class = 7
Traceback (most recent call last):
  File "run_class_finetuning.py", line 679, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 256, in main
    dataset_val, _ = build_dataset(is_train=False, test_mode=False, args=args)
  File "/opt/data/private/MAE-DFER-master/datasets.py", line 224, in build_dataset
    args=args)
  File "/opt/data/private/MAE-DFER-master/kinetics.py", line 331, in __init__
    self.label_array = list(cleaned.values[:, 1])
IndexError: index 1 is out of bounds for axis 1 with size 1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'run_class_finetuning.py', '--local_rank=1', '--model', 'vit_base_dim512_no_depth_patch16_160', '--depth', '16', '--data_set', 'DFEW', '--nb_classes', '7', '--data_path', './saved/data/dfew/split01', '--finetune', './saved/model/pretraining/voxceleb2/videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49.pth', '--log_dir', './saved/model/finetuning/dfew/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_split01_lr_1e-3_epoch_10_size160_sr4_classify_token_type_region_server164', '--output_dir', './saved/model/finetuning/dfew/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_split01_lr_1e-3_epoch_10_size160_sr4_classify_token_type_region_server164', '--batch_size', '8', '--num_sample', '1', '--input_size', '160', '--short_side_size', '160', '--save_ckpt_freq', '1000', '--num_frames', '16', '--sampling_rate', '4', '--opt', 'adamw', '--lr', '1e-3', '--opt_betas', '0.9', '0.999', '--weight_decay', '0.05', '--epochs', '10', '--dist_eval', '--test_num_segment', '2', '--test_num_crop', '2', '--attn_type', 'local_global', '--lg_region_size', '2', '5', '10', '--lg_classify_token_type', 'region', '--num_workers', '16']' returned non-zero exit status 1.


Here is an example of train.csv of my own dataset fold:
                /opt/data/private/dataset/0/162760190960914022 0
                /opt/data/private/dataset/0/162678346053216256 1
                /opt/data/private/dataset/0/162168466908905881 2
                ...
Here is the structure of the dataset fold:
                                             /opt/data/private/dataset/0/
                                                                                           162760190960914022/
                                                                                                                               1.jpg
                                                                                                                                ...
                                                                                                                                1234.jpg
                                                                                            162168466908905881/
                                                                                                                                1.jpg
                                                                                                                                 ...
                                                                                                                                 839.jpg

**Comment by sunlicai** [comment]
It seems that you did not change the value of the argument 'dataset' (i.e., 'DFEW') and register your dataset. 

For your own private dataset, it's necessary to register it in *dataset.py*. You check the default datasets such as DFEW and FERV39k as a reference. 

https://github.com/sunlicai/MAE-DFER/blob/c4dff47e6f48bcc1a57d13f39e3045b8dce7e3a7/datasets.py#L196-L226

Note that you should also add the dataset name in *run_class_finetuning.py*:

https://github.com/sunlicai/MAE-DFER/blob/c4dff47e6f48bcc1a57d13f39e3045b8dce7e3a7/run_class_finetuning.py#L165

Finally, you should adapt the running script of DFEW by specifying your own dataset name and the number of classes:

https://github.com/sunlicai/MAE-DFER/blob/c4dff47e6f48bcc1a57d13f39e3045b8dce7e3a7/scripts/dfew/finetune_local_global_attn_depth16_region_size2510_with_diff_target_164.sh#L4-L5

**Comment by dufan175** [comment]
Sorry to bother you again, i register my data in datasets.py, and i modified the run_class_finetuning.py according to your suggestion, but the same error still occurred.
Here is my code in datasets.py:
    elif args.data_set == 'MYDATA':
        mode = None
        anno_path = None
        if is_train is True:
            mode = 'train'
            anno_path = os.path.join(args.data_path, 'train.csv')
        elif test_mode is True:
            mode = 'test'
            anno_path = os.path.join(args.data_path, 'test.csv')
        else:
            mode = 'validation'
            anno_path = os.path.join(args.data_path, 'test.csv')

        dataset = VideoClsDatasetFrame(
            anno_path=anno_path,
            data_path='/',
            mode=mode,
            clip_len=args.num_frames,
            frame_sample_rate=args.sampling_rate,
            num_segment=1,
            test_num_segment=args.test_num_segment,
            test_num_crop=args.test_num_crop,
            num_crop=1 if not test_mode else 3,
            keep_aspect_ratio=True,
            crop_size=args.input_size,
            short_side_size=args.short_side_size,
            new_height=256, # me: actually no use
            new_width=320, # me: actually no use
            args=args)
        nb_classes = 3

**Comment by sunlicai** [comment]
Please paste the running log so that I can have more information to debug

**Comment by dufan175** [comment]
Oh, i have solved the error, it seems to be caused by an error in the train.csv generated by my dataset. But now there is an another error. Do you know what caused it? Here is the log:

optimizer settings: {'lr': 0.0003125, 'weight_decay': 0.0, 'eps': 1e-08, 'betas': [0.9, 0.999]}
Traceback (most recent call last):
  File "run_class_finetuning.py", line 679, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 516, in main
    print("Max WD = %.7f, Min WD = %.7f" % (max(wd_schedule_values), min(wd_schedule_values)))
ValueError: max() arg is an empty sequence
Use step level LR scheduler!
Set warmup steps = 0
Set warmup steps = 0
Traceback (most recent call last):
  File "run_class_finetuning.py", line 679, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 516, in main
    print("Max WD = %.7f, Min WD = %.7f" % (max(wd_schedule_values), min(wd_schedule_values)))
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'run_class_finetuning.py', '--local_rank=1', '--model', 'vit_base_dim512_no_depth_patch16_160', '--depth', '16', '--data_set', 'FERV39k', '--nb_classes', '3', '--data_path', './saved/data/mydata/all_scenes', '--finetune', './saved/model/pretraining/voxceleb2/videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49.pth', '--log_dir', './saved/model/finetuning/mydata/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_lr_1e-3_epoch_10_size160_sr1_classify_token_type_region_server164', '--output_dir', './saved/model/finetuning/mydata/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_lr_1e-3_epoch_10_size160_sr1_classify_token_type_region_server164', '--batch_size', '40', '--num_sample', '1', '--input_size', '160', '--short_side_size', '160', '--save_ckpt_freq', '1000', '--num_frames', '16', '--sampling_rate', '1', '--opt', 'adamw', '--lr', '1e-3', '--opt_betas', '0.9', '0.999', '--weight_decay', '0.05', '--epochs', '10', '--dist_eval', '--test_num_segment', '2', '--test_num_crop', '2', '--attn_type', 'local_global', '--lg_region_size', '2', '5', '10', '--lg_classify_token_type', 'region', '--num_workers', '16']' returned non-zero exit status 1.

**Comment by sunlicai** [comment]
The error is due to that 'wd_schedule_values' is an empty array. You can check what's wrong with func 'cosine_scheduler' in *utils.py*:

https://github.com/sunlicai/MAE-DFER/blob/c4dff47e6f48bcc1a57d13f39e3045b8dce7e3a7/utils.py#L385-L402

I guess it might be caused by the wrong 'epochs', 'warmup_epochs', or 'niter_per_ep'.

**Comment by dufan175** [comment]
Yes, i have solved the error by changing epochs. But there is an another error. Sorry to trouble you so many times.

optimizer settings: {'lr': 6.25e-05, 'weight_decay': 0.0, 'eps': 1e-08, 'betas': [0.9, 0.999]}
Use step level LR scheduler!
Set warmup steps = 5
Set warmup steps = 0
Max WD = 0.0500000, Min WD = 0.0500000
criterion = SoftTargetCrossEntropy()
Auto resume checkpoint: 
Start training for 10 epochs
WARNING:root:NaN or Inf found in input tensor.
Epoch: [0]  [0/1]  eta: 0:00:03  lr: 0.000000  min_lr: 0.000000  loss: 1.0986 (1.0986)  loss_scale: 32768.0000 (32768.0000)  weight_decay: 0.0500 (0.0500)  grad_norm: nan (nan)  time: 3.8819  data: 3.1720  max mem: 4503
Epoch: [0] Total time: 0:00:04 (4.7073 s / it)
Averaged stats: lr: 0.000000  min_lr: 0.000000  loss: 1.0986 (1.0987)  loss_scale: 32768.0000 (32768.0000)  weight_decay: 0.0500 (0.0500)  grad_norm: nan (nan)
Traceback (most recent call last):
  File "run_class_finetuning.py", line 681, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 597, in main
    test_stats = validation_one_epoch(data_loader_val, model, device)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/opt/data/private/MAE-DFER-master/engine_for_finetuning.py", line 166, in validation_one_epoch
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/usr/local/lib/python3.6/dist-packages/timm/utils/metrics.py", line 29, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26
Traceback (most recent call last):
  File "run_class_finetuning.py", line 681, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 597, in main
    test_stats = validation_one_epoch(data_loader_val, model, device)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/opt/data/private/MAE-DFER-master/engine_for_finetuning.py", line 166, in validation_one_epoch
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/usr/local/lib/python3.6/dist-packages/timm/utils/metrics.py", line 29, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'run_class_finetuning.py', '--local_rank=1', '--model', 'vit_base_dim512_no_depth_patch16_160', '--depth', '16', '--data_set', 'MYDATA', '--nb_classes', '3', '--data_path', './saved/data/mydata/all_scenes', '--finetune', './saved/model/pretraining/voxceleb2/videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49.pth', '--log_dir', './saved/model/finetuning/mydata/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_lr_1e-3_epoch_10_size160_sr1_classify_token_type_region_server164', '--output_dir', './saved/model/finetuning/mydata/voxceleb2_videomae_pretrain_base_dim512_local_global_attn_depth16_region_size2510_patch16_160_frame_16x4_tube_mask_ratio_0.9_e100_with_diff_target_server170/checkpoint-49/eval_lr_1e-3_epoch_10_size160_sr1_classify_token_type_region_server164', '--batch_size', '8', '--num_sample', '1', '--input_size', '160', '--short_side_size', '160', '--save_ckpt_freq', '1000', '--num_frames', '16', '--sampling_rate', '1', '--opt', 'adamw', '--lr', '1e-3', '--opt_betas', '0.9', '0.999', '--weight_decay', '0.05', '--epochs', '10', '--dist_eval', '--test_num_segment', '2', '--test_num_crop', '2', '--attn_type', 'local_global', '--lg_region_size', '2', '5', '10', '--lg_classify_token_type', 'region', '--num_workers', '16']' returned non-zero exit status 1.

**Comment by dufan175** [comment]
Oh, i have solved this error. Thank you for your patient guidance！
